<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PC-02" name="TestVerifySearch" tests="2" failures="1" timestamp="10 Sep 2015 12:41:54 GMT" time="12.48" errors="0">
  <testcase name="enterSearch" time="0.008" classname="org.testng.Tests.VerifySearch">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- enterSearch -->
  <testcase name="verifySearch" time="0.0" classname="org.testng.Tests.VerifySearch">
    <skipped/>
  </testcase> <!-- verifySearch -->
</testsuite> <!-- TestVerifySearch -->
